var gastoHoxe = 66.66;
var gastoOnte = 33.33;
var gastoMaña = 1.12;
//var total = gastoHoxe / gastoOnte / gastoMaña;
//var total = gastoHoxe + gastoOnte + gastoMaña;
//var total = gastoHoxe / gastoOnte * gastoMaña;
//var total = gastoHoxe * gastoOnte / gastoMaña;
//var total = gastoHoxe - gastoOnte + gastoMaña;
var total = gastoHoxe + gastoOnte - gastoMaña;
alert(total);